### ISSUE TITLE
Propriedade paid 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/market#14]
Boa tarde Talisson, estávamos fazendo a view do market, porém nos deparamos com a situação que o Melhor envio está setado como Pago, ele deve ser gratuito. Além disso, precisamos que tenha uma propriedade que se for pago, precisamos ter esse valor, para mostrar pro usuário e futuramente utiliza-lo nas cobranças, por isso precisamos de tê-lo.

**Comment by talissonf** [comment]
@matheusgnreis  atualizei o melhor envio pra free como você pediu e sobre os planos é o seguinte, no market os apps tem as seguintes propriedades `free_trial (boolean)`, `plans_json(object|json)` e `value_plan_basic (int)`. Eu nunca usei essas propriedades porque nunca foi definido como os aplicativo pagos iriam funcionar. Esse `plans_json` é uma propriedade pros planos do app mais também não foi definido como seria o schema dele. Podemos definir juntos que ja implemento no market.

**Comment by matheusgnreis** [comment]
Free trial e value plan basic é de boa né. Agora plans_json o que você acha interessante ter nele, pois vejo mais ou menos o que pensa e penso em mais algumas coisas também, acho que facilita o processo de decidirmos dessa forma

**Comment by talissonf** [comment]
Acho que seria algo assim

```javascript
[{
  "title": "Plano Free",
  "short_description": "No plano free você pode usar todas as funcionalidades abaixo",
  "description": "Funcionalidade 1 ",
  "free": true
},
{
  "title": "Plano Start",
  "short_description": "No plano start você pode usar todas as funcionalidades abaixo",
  "description": "Funcionalidade 1/ funcionalidade 2/ funcionalidade 3",
  "free": false,
  "plan": {
    "price": 49,
    "recurrence": "monthly",
    "free_trial": {
      "enable": false,
      "in_day": 7
    }
  }
}]
```
Acho que seria bom pensar sobre a propriedade description, aceitar um MD ou um HTML pra renderizar uma lista, talvez.

**Comment by matheusgnreis** [comment]
Bom dia, ou achei que ficou bom a estrutura inserida, até porque o desenvolvedor pode criar mais de um plano, seja com valores diferentes e funcionalidades diferentes, ou semestral, anual. Depois vou consultar a API de algum intermediador para verificar como eles especificam isso. Se for mensalmente envia-se o que? Depois verifico e passo. Acredito que a estrutura esteja boa e a descrição aceite MD. Tem um componente em vue que renderiza MD, então acho que facilita. Mas se tiver um em html, não vejo problema. O trial ficou bacana, pois em plano pago normalmente tem um trial e a quantidade de dias que é gratuito antes da cobrança. Acho que não foge disso, ficou muito bom. Parabens!
