### ISSUE TITLE
[RFC] Schema improves

### ISSUE THREAD

**Issue by leomp12** [ecomplus/market#26]
https://github.com/ecomplus/application-starter/issues/4#issuecomment-587929249

Talvez seja interessante fazer uma `v2` da API pra não quebrar as implementações atuais, mas tô achando este [schema](https://github.com/ecomclub/market/blob/master/assets/schemas/applications.json) meio confuso...

É uma "cópia" do schema do Application da Store API com alguns (ou só o `admin_settings`?) campos renomeados, alguns campos a mais, e que além disto deverá ser atualizado manualmente pra seguir atualizações na Store API, se houverem.

Minha sugestão é ter um field `store_app` (ou algo do tipo), que simplesmente aceite um JSON qualquer (a Store API que vai validar), além dos fields para o Market. Então teríamos algo como:

```json
{
  "id": 123,
  "icon": "https://ksdncsdkl.jpg",
  "slug": "my-market",
  "title": "Meu app",
  "author": "Fulano",
  "store_app": { ... },
  ...
}
```

Alguns fields seriam duplicados, mas acho que isto não é um problema de todo.
Talvez podemos deixar estes campos duplicados (como `title`) como opcionais dentro do `store_app` no POST/PUT, aí se `store_app.title` não for definido (por exemplo), copiamos o `title` no root do objeto (ficou muito confuso?).

O que você acha @talissonf ?

**Comment by talissonf** [comment]
Eu entendi, pode ser dessa forma, fica melhor esse tipo de organização.

**Comment by leomp12** [comment]
Certo, consegue priorizar isto?
Vou manter https://github.com/ecomplus/application-starter/issues/4 bloqueado por enquanto.

> Cuidado com breaking changes, **sugiro fortemente que seja uma `v2` da API**.

**Comment by talissonf** [comment]
Mas vai ser uma v2 mesmo.

**Comment by talissonf** [comment]
Estou limitando a V1 apenas ao método GET, e deixei os outros métodos liberados na V2, pois fiz algumas alterações no banco de dados e não queria ter que manter duas tabela para aplicativos.

**Comment by leomp12** [comment]
@talissonf fechado
Mas você já publicou isto? [Aqui](https://github.com/ecomplus/market/blob/master/assets/schemas/applications.json) segue o schema antigo eu acho.

**Comment by talissonf** [comment]
@leomp12 não publiquei ainda, tô finalizando a v2 publico tudo.
