### ISSUE TITLE
[RFC] Market/Partner

### ISSUE THREAD

**Issue by talissonf** [ecomplus/market#30]
Precisamos fazer algumas alterações no front-end do market, principalmente nas view relacionadas ao partner. Gostaria de sugestões para melhorar a experiência do parceiro nos fluxos de inclusão e edição de app.

**Comment by leomp12** [comment]
Vou listar umas coisas que eu já vi aqui:

- [ ] Falta um destaque para o login de parceiro no header, talvez o ideal seja um botão login com dropdown que abra dois links, um para o login de parceiro e um para login de lojista;

- [ ] Por enquanto acho que podemos remover _temas_ e _widgets_ do header;

- [ ] Tentando acessar o link da página de parceiro sem login o usuário é somente redirecionado para a home, é importante abrir a popup de login neste ponto, talvez você possa adicionar um hash na home que triga o modal, tipo `https://market.e-com.plus/#login`;

- [ ] Na formulário de criação de app os textos são muito longos, acho que podemos resumir os help texts (textos longos podem ficar em artigos externos e serem linkados) dos campos mantidos e talvez reposicioná-los pra baixo dos labels.

- [ ] Alguns fields não são necessários na criação do app e acho que geram confusão pra quem está começando:
    - Acredito que podemos manter apenas _Título_, _Categoria_, _URL de redirecionamento_, _URL de callback para autenticação_, _Escopo de autenticação_, _Site do aplicativo_, _Ícone_, _Descrição curta_, _Descrição_, _Módulos_;
    - _Slug_ pode ser gerado automaticamente a partir do título;
   - O booleano _Autenticação_ pode ser true se houver URL de callback definido;
   - O escopo pode ser editável mas com padrão `GET stores/me` & `POST procedures`;
   - A _Versão_ pode ser `0.1.0` por padrão;
   - Nos _Módulos_, quando adicionado ele já pode estar habilitado por padrão;
   - Outras configurações podemos deixar somente via JSON e talvez no formulário de edição (talvez este pode ser um pouco mais extenso que o de criação);

- [ ] Tanto na criação quanto na edição, é importante que a aba com o JSON mostre os valores correspondentes ao preenchido no formulário (se não confude), talvez o schema possa ficar em outra aba ou em um accordion. Acho que ela podemos renomeá-la também, acredito JSON não é avançado para desenvolvedores, talvez só _JSON_ mesmo;

- [ ] Tornar o painel do parceiro responsivo e melhorar a experiência em mobile;

**Comment by leomp12** [comment]
Oi @talissonf ,
Vi os checks agora, tá tudo pronto aqui?

**Comment by talissonf** [comment]
@leomp12 eu fui marcando enquanto eu fui fazendo esses ajustes mas não commitei, vou fazer isso agora.

**Comment by talissonf** [comment]
@leomp12 publicado.

**Comment by leomp12** [comment]
Boa @talissonf , ficou bacana, valeu!

**Comment by leomp12** [comment]
@talissonf notei uns detalhes: 

1. Criando um applicativo (talvez editando também), no _Authentication scope_ o botão salvar não funciona e o fechar mantém salvo, de qualquer forma acho que nem precisa de dois botões, precisa?
2. Na edição do app acho que seria bacana mostrar um input com a versão, acho que faz sentido editar a versão quando o app é alterado, dá colocar só na edição?
3. Na edição do app, quando há admin settings eles aparecem logo abaixo dos módulos sem nenhuma separação...

**Comment by leomp12** [comment]
@matheusgnreis @vitorrgg podem testar e opinar pra nós também por favor?

**Comment by talissonf** [comment]
> @talissonf notei uns detalhes:
> 
> 1. Criando um applicativo (talvez editando também), no _Authentication scope_ o botão salvar não funciona e o fechar mantém salvo, de qualquer forma acho que nem precisa de dois botões, precisa?
> 2. Na edição do app acho que seria bacana mostrar um input com a versão, acho que faz sentido editar a versão quando o app é alterado, dá colocar só na edição?
> 3. Na edição do app, quando há admin settings eles aparecem logo abaixo dos módulos sem nenhuma separação...

Pronto :flower_playing_cards:
