### ISSUE TITLE
Templates de E-mail

### ISSUE THREAD

**Issue by talissonf** [ecomplus/market#34]
O market está enviando e-mail para o parceiro agora, na criação do cadastro e também na recuperação de senha. Eu fiz esses dois templates no mailjet na conta da ecom, apenas para publicar a versão do market. https://github.com/ecomplus/market/tree/master/templates/emails.
Favor alterá-los e fazer uma PR no market quando estiverem prontos.

@vitorrgg ou @matheusgnreis

**Comment by talissonf** [comment]
Também preciso dos dados de alguma conta de e-mail para disparar os e-mails pelo market.

**Comment by matheusgnreis** [comment]
@vitorrgg dá uma olhada nisso para nós

**Comment by leomp12** [comment]
Progredimos com isto @vitorrgg ? Quais dados você precisa @talissonf ?

**Comment by talissonf** [comment]
@leomp12 os templates tão prontos já. Só falta os dados da conta de email.

**Comment by talissonf** [comment]
Eu vou usar o mailjet pra disparar os e-mails, vou implementar isso e fecho o issue.

**Comment by leomp12** [comment]
Isso aqui tá fechado @talissonf ?

**Comment by talissonf** [comment]
sim
